ARG BASE_IMAGE=ghcr.io/pravidhico/flutter_stable_base:latest

FROM --platform=$BUILDPLATFORM ${BASE_IMAGE}

ENV FLUTTER_HOME=/home/ci/flutter-sdk

USER 0

# Linux support
RUN microdnf update -y && \
    microdnf --setopt=install_weak_deps=0 \
        install -y \
        ninja-build \
        gtk3-devel && \
    microdnf clean all

USER ci

RUN flutter precache --linux || flutter doctor
