FROM --platform=$BUILDPLATFORM ghcr.io/pravidhico/flutter_stable_base:latest

ENV ANDROID_SDK_TOOLS_VERSION=15859902
ENV ANDROID_NDK_VERSION=28.2.13676358
ENV ANDROID_HOME=/opt/android
ENV ANDROID_PLATFORM_VERSION=36
ENV ANDROID_BUILD_TOOLS_VERSION=36.0.0
ENV FLUTTER_HOME=/opt/flutter

ENV PATH=${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/emulator

RUN dnf update -y && \
    dnf --setopt=install_weak_deps=False \
        install -y \
        java-21-openjdk-devel \
        make \
        cmake \
        clang \
        diffutils && \
    dnf clean all

RUN wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS_VERSION}_latest.zip -O android-sdk-tools.zip && \
    mkdir -p ${ANDROID_HOME}/cmdline-tools/ && \
    unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}/cmdline-tools/ && \
    rm android-sdk-tools.zip && \
    mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest && \
    yes | sdkmanager --licenses && \
    yes | sdkmanager \
      "platforms;android-$ANDROID_PLATFORM_VERSION" \
      "build-tools;$ANDROID_BUILD_TOOLS_VERSION" \
      "ndk;$ANDROID_NDK_VERSION"

RUN git config --global --add safe.directory ${FLUTTER_HOME} && \
    flutter config --no-analytics && \
    flutter --disable-analytics && \
    flutter precache || flutter doctor
